task: fg

model:
  inp_emb_size: 32
  instance_feat_channels: 8
  instance_feat_hidden: 64
  loss_type: smoothl1
  mask_crossent_coef: 0.0
  mask_distill_coef: 1.0
  mask_head:
    maskrcnn_pretrain_path: null
    no_finetune: true
  model_type: segbbox_independent_ed
  num_convlstm_layers: 2
  num_traj_out_layers: 2
  rnn_hidden: 128
  rnn_type: gru
  traj_coef: 0.1
  traj_feat_channels: 16
  use_depth_inp: true
  use_full_instance_traj_inp: true
  use_odometry: true

training:
  batch_size: 32
  clip_grad_norm: 5.0
  lr: 0.0005
  lr_decay_factor: 0.1
  lr_decay_steps: 250
  lr_scheduler_type: step
  num_data_workers: 4
  num_epochs: 500
  steps_per_epoch: 400
  use_adam: true
