# Copyright Niantic 2021. Patent Pending. All rights reserved.
#
# This software is licensed under the terms of the Panoptic Forecasting licence
# which allows for non-commercial use only, the full terms of which are made
# available in the LICENSE file.

task: scene_only

data:
  dataset_type: odom
  data_splits: ['val']
  data_dir: data/fg/

training:
  num_data_workers: 4
  batch_size: 32